<a href="https://colab.research.google.com/github/teddy-teem/deep-learning/blob/master/NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




In [ ]:
features = torch.rand(10,5)
model = Model(features.shape[1]);

# simply call as like this, it will automatically trigged the forward
model(features)

tensor([[0.4140],
        [0.3736],
        [0.4043],
        [0.4697],
        [0.4399],
        [0.5115],
        [0.3988],
        [0.4750],
        [0.4652],
        [0.4525]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.1455, -0.4223, -0.2249, -0.0404, -0.2510]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

In [ ]:
summary(model, input_size=(10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class MyModel(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out




In [ ]:
features = torch.rand(10,5)
model = MyModel(features.shape[1]);

# simply call as like this, it will automatically trigged the forward
model(features)

tensor([[0.3900],
        [0.3944],
        [0.3857],
        [0.3854],
        [0.3905],
        [0.3851],
        [0.3853],
        [0.3905],
        [0.3884],
        [0.3905]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class SequencialModel(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid(),
    )

  def forward(self, features):
    out = self.network(features)
    return out




In [ ]:
features = torch.rand(10,5)
model = SequencialModel(features.shape[1]);

# simply call as like this, it will automatically trigged the forward
model(features)

tensor([[0.5940],
        [0.5921],
        [0.5869],
        [0.5869],
        [0.5869],
        [0.5869],
        [0.5800],
        [0.5955],
        [0.5913],
        [0.5869]], grad_fn=<SigmoidBackward0>)

# Train Cancer Dataset

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
562       15.220         30.62          103.40      716.9          0.10480   
111       12.630         20.76           82.15      480.4          0.09933   
13        15.850         23.95          103.70      782.7          0.08401   
509       15.460         23.95          103.80      731.3          0.11830   
318        9.042         18.90           60.07      244.5          0.09968   
..           ...           ...             ...        ...              ...   
192        9.720         18.22           60.73      288.1          0.06950   
22        15.340         14.26          102.50      704.4          0.10730   
323       20.340         21.51          135.90     1264.0          0.11700   
418       12.700         12.17           80.88      495.0          0.08785   
64        12.680         23.84           82.69      499.0          0.11220   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
562           0.20870         0.25500              0.09429         0.2128   
111           0.12090         0.10650              0.06021         0.1735   
13            0.10020         0.09938              0.05364         0.1847   
509           0.18700         0.20300              0.08520         0.1807   
318           0.19720         0.19750              0.04908         0.2330   
..                ...             ...                  ...            ...   
192           0.02344         0.00000              0.00000         0.1653   
22            0.21350         0.20770              0.09756         0.2521   
323           0.18750         0.25650              0.15040         0.2569   
418           0.05794         0.02360              0.02402         0.1583   
64            0.12620         0.11280              0.06873         0.1905   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
562                 0.07152  ...        17.520          42.79   
111                 0.07070  ...        13.330          25.47   
13                  0.05338  ...        16.840          27.66   
509                 0.07083  ...        17.110          36.33   
318                 0.08743  ...        10.060          23.40   
..                      ...  ...           ...            ...   
192                 0.06447  ...         9.968          20.83   
22                  0.07032  ...        18.070          19.08   
323                 0.06670  ...        25.300          31.86   
418                 0.06275  ...        13.650          16.92   
64                  0.06590  ...        17.090          33.47   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
562           128.70       915.0           0.14170            0.79170   
111            89.00       527.4           0.12870            0.22500   
13            112.00       876.5           0.11310            0.19240   
509           117.70       909.4           0.17320            0.49670   
318            68.62       297.1           0.12210            0.37480   
..               ...         ...               ...                ...   
192            62.25       303.8           0.07117            0.02729   
22            125.10       980.9           0.13900            0.59540   
323           171.10      1938.0           0.15920            0.44920   
418            88.12       566.9           0.13140            0.16070   
64            111.80       888.3           0.18510            0.40610   

     concavity_worst  concave points_worst  symmetry_worst  \
562          1.17000               0.23560          0.4089   
111          0.22160               0.11050          0.2226   
13           0.23220               0.11190          0.2809   
509          0.59110               0.21630          0.3013   
318          0.46090               0.11450          0.3135   
..               ...                   ...             ...   
192          0.00000               0.00000         

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
loss_function = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
model = MySimpleNN(X_train_tensor.shape[1])

for epoch in range(epochs):
  y_pred = model(X_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
  loss.backward()
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.5911583304405212
Epoch: 2, Loss: 0.47665834426879883
Epoch: 3, Loss: 0.4097473621368408
Epoch: 4, Loss: 0.36512401700019836
Epoch: 5, Loss: 0.33277902007102966
Epoch: 6, Loss: 0.3080034852027893
Epoch: 7, Loss: 0.2882709801197052
Epoch: 8, Loss: 0.27209317684173584
Epoch: 9, Loss: 0.25853028893470764
Epoch: 10, Loss: 0.24695652723312378
Epoch: 11, Loss: 0.23693719506263733
Epoch: 12, Loss: 0.22815974056720734
Epoch: 13, Loss: 0.2203928530216217
Epoch: 14, Loss: 0.21346122026443481
Epoch: 15, Loss: 0.20722922682762146
Epoch: 16, Loss: 0.20159003138542175
Epoch: 17, Loss: 0.1964581161737442
Epoch: 18, Loss: 0.19176426529884338
Epoch: 19, Loss: 0.18745151162147522
Epoch: 20, Loss: 0.18347273766994476
Epoch: 21, Loss: 0.17978841066360474
Epoch: 22, Loss: 0.17636524140834808
Epoch: 23, Loss: 0.17317481338977814
Epoch: 24, Loss: 0.17019282281398773
Epoch: 25, Loss: 0.16739831864833832


In [ ]:
model2 = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model2.parameters(), lr=learning_rate)

for epoch in range(epochs):
  y_pred = model(X_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.1647731065750122
Epoch: 2, Loss: 0.1647731065750122
Epoch: 3, Loss: 0.1647731065750122
Epoch: 4, Loss: 0.1647731065750122
Epoch: 5, Loss: 0.1647731065750122
Epoch: 6, Loss: 0.1647731065750122
Epoch: 7, Loss: 0.1647731065750122
Epoch: 8, Loss: 0.1647731065750122
Epoch: 9, Loss: 0.1647731065750122
Epoch: 10, Loss: 0.1647731065750122
Epoch: 11, Loss: 0.1647731065750122
Epoch: 12, Loss: 0.1647731065750122
Epoch: 13, Loss: 0.1647731065750122
Epoch: 14, Loss: 0.1647731065750122
Epoch: 15, Loss: 0.1647731065750122
Epoch: 16, Loss: 0.1647731065750122
Epoch: 17, Loss: 0.1647731065750122
Epoch: 18, Loss: 0.1647731065750122
Epoch: 19, Loss: 0.1647731065750122
Epoch: 20, Loss: 0.1647731065750122
Epoch: 21, Loss: 0.1647731065750122
Epoch: 22, Loss: 0.1647731065750122
Epoch: 23, Loss: 0.1647731065750122
Epoch: 24, Loss: 0.1647731065750122
Epoch: 25, Loss: 0.1647731065750122


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.2157,  0.2376,  0.2273,  0.0971,  0.1377,  0.1512,  0.3012,  0.1158,
         -0.0236, -0.1592,  0.2954, -0.0708,  0.2803,  0.1758, -0.0154, -0.0295,
         -0.0795,  0.0332,  0.1055, -0.1025,  0.2478,  0.2888,  0.0899,  0.3570,
          0.1397,  0.1731,  0.3219,  0.3376,  0.0873,  0.1152]],
       requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model2.forward(X_test_tensor)
  y_pred = (y_pred > 0.7).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.632964015007019
