<a href="https://colab.research.google.com/github/teddy-teem/deep-learning/blob/master/Tensor_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import time

In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
  device = torch.device("cuda")
else:
  print("GPU is not available")


GPU is available
Using GPU: Tesla T4


In [ ]:
a = torch.empty(2,3)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.0974, 0.5832, 0.0422],
        [0.4452, 0.3227, 0.9180]])

In [ ]:
torch.rand(2,3)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([1,2,3,54])

tensor([ 1,  2,  3, 54])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
x = torch.tensor([[1,2],[2,3]])
x.shape

torch.Size([2, 2])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067527568732466485],
        [4049363015109849393, 6499592770363274798]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1]])

torch.rand() generate float type data. here x is int that why it throw errors

In [ ]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
y = torch.tensor([[1., 2.], [2., 3.]])
torch.rand_like(y)

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
torch.rand_like(x.to(torch.float))

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

In [ ]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])

**Operations**

In [ ]:
x+2

tensor([[3, 4],
        [4, 5]])

In [ ]:
x-2

tensor([[-1,  0],
        [ 0,  1]])

In [ ]:
x*2

tensor([[2, 4],
        [4, 6]])

In [ ]:
x/2

tensor([[0.5000, 1.0000],
        [1.0000, 1.5000]])

In [ ]:
x//2

tensor([[0, 1],
        [1, 1]])

In [ ]:
x%2

tensor([[1, 0],
        [0, 1]])

In [ ]:
x**2

tensor([[1, 4],
        [4, 9]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
a+b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [ ]:
a-b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [ ]:
a*b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [ ]:
a/b

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [ ]:
a%b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [ ]:
torch.abs(a)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [ ]:
torch.round(a)

tensor([[0., 0., 0.],
        [1., 1., 1.]])

In [ ]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.clamp(a, min=0.5, max=0.7)

tensor([[0.5000, 0.5000, 0.5000],
        [0.7000, 0.5557, 0.7000]])

In [ ]:
torch.sum(a)

tensor(3.0613)

In [ ]:
torch.sum(a, dim=1)

tensor([0.7047, 2.3566])

In [ ]:
torch.mean(a)

tensor(0.5102)

In [ ]:
torch.std(a)

tensor(0.3328)

In [ ]:
torch.var(a)

tensor(0.1107)

In [ ]:
torch.argmin(a)

tensor(2)

In [ ]:
torch.argmax(a)

tensor(5)

In [ ]:
o = torch.tensor([[1., -1.2, .23, 1.2, -1.5], [1., -1.2, .23, 1.2, -1.5]])
print(o)
ans = torch.softmax(o, dim=0)
print(ans)

tensor([[ 1.0000, -1.2000,  0.2300,  1.2000, -1.5000],
        [ 1.0000, -1.2000,  0.2300,  1.2000, -1.5000]])
tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])


In [ ]:
torch.relu(o)

tensor([[1.0000, 0.0000, 0.2300, 1.2000, 0.0000],
        [1.0000, 0.0000, 0.2300, 1.2000, 0.0000]])

In [ ]:
o.relu_()
print(o)

tensor([[1.0000, 0.0000, 0.2300, 1.2000, 0.0000],
        [1.0000, 0.0000, 0.2300, 1.2000, 0.0000]])


In [ ]:
x = o.clone() # deep copy;
print(x)

tensor([[1.0000, 0.0000, 0.2300, 1.2000, 0.0000],
        [1.0000, 0.0000, 0.2300, 1.2000, 0.0000]])


How to perform Tensor OP on GPU

In [ ]:
print(device)

cuda


In [ ]:
torch.rand(2,3, device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
b = x.to(device)
print(b)

tensor([[1.0000, 0.0000, 0.2300, 1.2000, 0.0000],
        [1.0000, 0.0000, 0.2300, 1.2000, 0.0000]], device='cuda:0')


In [ ]:
b + 5

tensor([[6.0000, 5.0000, 5.2300, 6.2000, 5.0000],
        [6.0000, 5.0000, 5.2300, 6.2000, 5.0000]], device='cuda:0')

In [ ]:
size = 10000

matrix1_cpu = torch.rand(size, size)
matrix2_cpu = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix1_cpu, matrix2_cpu)
cpu_time = time.time() - start_time
print(f"CPU time: {cpu_time} seconds")


CPU time: 15.465413808822632 seconds


In [ ]:
matrix1_gpu = matrix1_cpu.to(device=device)
matrix2_gpu = matrix2_cpu.to(device=device)

start_time = time.time()
result_gpu = torch.matmul(matrix1_gpu, matrix2_gpu)
gpu_time = time.time() - start_time
print(f"GPU time: {gpu_time} seconds")

GPU time: 0.0006835460662841797 seconds


In [ ]:
speedup = cpu_time / gpu_time
print(f"Speedup: {speedup}x")

Speedup: 22625.269271014997x


In [ ]:
b = torch.rand(4,4)
b

tensor([[0.1698, 0.0098, 0.7602, 0.0348],
        [0.4903, 0.4229, 0.4088, 0.2302],
        [0.1046, 0.1465, 0.7036, 0.8185],
        [0.6261, 0.2405, 0.5844, 0.7472]])

In [ ]:
b.reshape(2,2,2,2)

tensor([[[[0.1698, 0.0098],
          [0.7602, 0.0348]],

         [[0.4903, 0.4229],
          [0.4088, 0.2302]]],


        [[[0.1046, 0.1465],
          [0.7036, 0.8185]],

         [[0.6261, 0.2405],
          [0.5844, 0.7472]]]])

In [ ]:
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c = torch.rand(226, 226, 3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

tensor to numpy

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.8245, 0.4418, 0.9953],
        [0.4155, 0.7811, 0.1746]])

In [ ]:
b = a.numpy()
type(b)

numpy.ndarray